### ISSUE TITLE
Cannot access user profile and list of users

### ISSUE THREAD

**Issue by harrychenca** [vivientam/diabetes#12]
![screen shot 2015-01-07 at 8 58 14 am](https://cloud.githubusercontent.com/assets/1697380/5639083/68825778-964b-11e4-9f30-fb90c83e32c7.png)

![screen shot 2015-01-07 at 8 57 59 am](https://cloud.githubusercontent.com/assets/1697380/5639092/8570b654-964b-11e4-9a3b-ccc57a2bbdda.png)

**Comment by vivientam** [comment]
Noted and working on it! :)
